services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: http
      - key: N8N_HOST
        value: your-app.onrender.com
      - key: WEBHOOK_TUNNEL_URL
        value: https://your-app.onrender.com
