version: '3.7'
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
